cc_library(
    name = 'double-conversion',
    srcs = [
        'bignum.cc',
        'bignum-dtoa.cc',
        'cached-powers.cc',
        'double-to-string.cc',
        'fast-dtoa.cc',
        'fixed-dtoa.cc',
        'string-to-double.cc',
        'strtod.cc'
	],
    #prebuilt=True,
    deps=[
        '#m',
    ]
)
